version: '1.0'

services:
  web:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - "./examples/simple-web-app/html:/usr/share/nginx/html"
    environment:
      - NGINX_PORT=80
    depends_on:
      - api
    
  api:
    image: "node:18-alpine"
    ports:
      - "3000:3000"
    volumes:
      - "./api:/app"
    working_dir: "/app"
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    depends_on:
      - db
      
  db:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_DB=webapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  db_data:

networks:
  default:
    driver: bridge