version: '1.0'

services:
  api:
    image: "node:18-alpine"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
    
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379