version: '1.0'

services:
  web:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - "./html:/usr/share/nginx/html:ro"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  app:
    image: "node:18-alpine"
    ports:
      - "3000:3000"
    volumes:
      - "./app:/usr/src/app"
    working_dir: "/usr/src/app"
    command: ["node", "server.js"]
    environment:
      - NODE_ENV=development
      - PORT=3000